#+LATEX_HEADER: \usepackage{amsthm}

\newtheoremstyle{defnstyle}{}{}{}{}{\scshape}{.}{\newline}{}

\theoremstyle{defnstyle}
\newtheorem{defn}{Definition}

* The Lectures

** Manifolds

Cryptically: a manifold is locally Euclidean. Let's take this as our
starting point rather than, as with some approaches, start with the
definition of a set, a topology, a topological manifold and finally a
differential manifold.

We need to relate a set to Euclidean space:

\begin{defn}[Co-ordinate Chart]
A co-ordinate chart on a set $X$ is a subset $U \subseteq X$
and a bijection

$$
\phi: U \longrightarrow \phi(U) \subseteq \mathbb{R}^n
$$

onto an open\footnote{Pre-requisites: what is a
topololgy, what is an open set, what is a continuous function} set $\phi(U)$ of $\mathbb{R}^n$.
\end{defn}

These bijections had better be compatible:

\begin{defn}[Atlas]
An atlas is a collection of co-ordinate charts $\{U_\alpha, \phi_\alpha\}_{\alpha \in I}$ such that

 1. $X$ is covered by the $\{U_\alpha, \phi_\alpha\}_{\alpha \in I}$.
 2. $\forall \alpha, \beta \in I$ , $\phi_\alpha(U_\alpha \cap U_\beta)$ is open in $\mathbb{R}^n$.
 3. The map $$\phi_\beta \circ \phi_\alpha^{-1}: \phi_\alpha(U_\alpha
    \cap U_\beta) \longrightarrow \phi_\beta(U_\alpha \cap U_\beta)$$
    is $C^\infty$ with $C^\infty$ inverse.
\end{defn}

 1. $X$ is covered by the $\{U_\alpha, \phi_\alpha\}_{\alpha \in I}$.
 2. $\forall \alpha, \beta \in I$ , $\phi_\alpha(U_\alpha \cap U_\beta)$ is open in $\mathbb{R}^n$.
 3. The map $$\phi_\beta \circ \phi_\alpha^{-1}: \phi_\alpha(U_\alpha
    \cap U_\beta) \longrightarrow \phi_\beta(U_\alpha \cap U_\beta)$$
    is $C^\infty$ with $C^\infty$ inverse.

* The Einstein Field Equations

$$
S_{EH} = \int {\mathcal{L}}_{EH}\sqrt{-g}\,\mathrm{d}^4 x
$$

To start with let's take ${\mathcal{L}}_{EH} = R$ where $R$ is the Ricci scalar.

* A General Relativity Bibliography

I started with cite:o1983semi which I still think is the best but
really quite hard going. It comes the closest to explaining what an
observer is. It stays away from overuse of indices. I think one only
needs to read chapters 1--6, 12 and 13.

For differential forms I read cite:darling_1994 but it doesn't cover
relativity.

These cite:tong-gr-lecture-notes are pretty good but I didn't really
follow his introductory chapter and skipped most of it. Maybe I could
now get more out of it. He doesn't say what an observer is but he does
use forms for some calculations instead of the raw curvature tensor to
make things easier.

** Phil's Bibliography

 1. cite:needham:2021DifferentialGeometry
 2. cite:needham:1998complex
 3. cite:needham:2023ComplexAnalysis

bibliography:DiffGeom.bib
bibliographystyle:unsrt

* A Proposal

I'd like to run a series of workshops (this might not be the right
name) in which everyone contributes to our collective understanding of
General Relativity.

I'd like the end goal to be: how do gravitational waves get generated
by binary stars for example and how did LIGO actually detect such
waves. I'd like to avoid the "tensor is as a tensor does approach" but
this may not be entirely possible.

There's a lot of stuff we'd have to understand on the way
(e.g. variational principles and differential geometry) and we might
not actually get there. But if you don't start something you never get
there.

Rather than spending a year creating notes that never see the light of
day, I am proposing we set off without the notes for gravitational
waves and create them as we go along.

I can certainly start the ball rolling with a talk on "Is a Straight
Lines Always the Shortest Distance: Some Steps Towards General
Relativity". The idea would be go through some concepts from
differential geometry and even write down the Einstein Equation whilst
noting down which concepts need to be explained in further workshops.

1. I am in and would like to prepare some material.
2. I'd like to participate but can't (yet) commit to preparing material.
3. This is too pretentious for words.

I assume I can somehow book a room in the University but maybe only
Dan or Barry can do that. I see no harm in advertising it within the
University and possibly more widely. Who knows? An expert on GR may
live locally and be keen to share their knowledge.

* Course Contents

** Prerequisites

Obviously multivariate calculus.

Linear algebra to some level.

** Topics

 1. What is a manifold
 2. Cotangent Space
 3. Tangent Space
 4. Vector Fields
 5. Differential Forms
 6. Tensors(?)
 7. Connections (via principal bundles? This may be taking things too far so probably just affine connections).
 8. Theorem Egregium (nothing to do with relativity but fun).
 9. Connections with torsion (Mercator).
 10. Geodesics aka straight lines.
 11. Metrics - compatatibility with the connection.
 12. Levi-Civita.
 13. Schwarzschild metric.
 14. Perihelion of Mercury
 15. Gravitational time dilation.
 16. Red shift (not sure I care about this).
 17. Stress Energy tensor - electromagnetism as the example - can we
     use a Nelkon example?
 18. Principle of Least Action.
 19. Einstein Equations via least action.
 20. Gravitational waves as a solition to the Einstein equations.
 21. Sources of gravitational waves: binary systems (stars, black holes).


* Some Random Links

This section is for my working notes.

https://www.quora.com/What-is-the-geometric-interpretation-of-the-concept-of-Connection-in-differential-geometry



